### ISSUE TITLE
ability to push to github

### ISSUE THREAD

**Issue by ChristopherBarrington** [ChristopherBarrington/scamp#7]
completed workbook/webpage reports could be pushed to a (or multiple) GitHub repositories

maybe specified with:

```yaml
    github:
        remotes:
          - ChristopherBarrington/scamp-push-test:babs/docs
```

is it worth having multiple remotes? maybe would have a public/private version of reports to different remotes?
